// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignInValidEmailValidPasswordTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signInValidEmailValidPassword() {
    // Test name: SignIn_ValidEmail_ValidPassword
    // Step # | name | target | value
    // 1 | open | /index.php | 
    driver.get("http://automationpractice.com/index.php");
    // 2 | setWindowSize | 697x728 | 
    driver.manage().window().setSize(new Dimension(697, 728));
    // 3 | click | linkText=Sign in | 
    driver.findElement(By.linkText("Sign in")).click();
    // 4 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 5 | type | id=email | AbundaBoy@gmail.com
    driver.findElement(By.id("email")).sendKeys("AbundaBoy@gmail.com");
    // 6 | click | id=passwd | 
    driver.findElement(By.id("passwd")).click();
    // 7 | type | id=passwd | boyboyabunda
    driver.findElement(By.id("passwd")).sendKeys("boyboyabunda");
    // 8 | click | css=#SubmitLogin > span | 
    driver.findElement(By.cssSelector("#SubmitLogin > span")).click();
    // 9 | click | linkText=Sign out | 
    driver.findElement(By.linkText("Sign out")).click();
    // 10 | close |  | 
    driver.close();
  }
}
