// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignUpTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signUp() {
    // Test name: Sign Up
    // Step # | name | target | value
    // 1 | open | /index.php | 
    driver.get("http://automationpractice.com/index.php");
    // 2 | setWindowSize | 697x735 | 
    driver.manage().window().setSize(new Dimension(697, 735));
    // 3 | click | linkText=Sign in | 
    driver.findElement(By.linkText("Sign in")).click();
    // 4 | click | id=email_create | 
    driver.findElement(By.id("email_create")).click();
    // 5 | type | id=email_create | AbundaBoy@gmail.com
    driver.findElement(By.id("email_create")).sendKeys("AbundaBoy@gmail.com");
    // 6 | click | css=#SubmitCreate > span | 
    driver.findElement(By.cssSelector("#SubmitCreate > span")).click();
    // 7 | click | id=id_gender1 | 
    driver.findElement(By.id("id_gender1")).click();
    // 8 | click | id=customer_firstname | 
    driver.findElement(By.id("customer_firstname")).click();
    // 9 | type | id=customer_firstname | Boy
    driver.findElement(By.id("customer_firstname")).sendKeys("Boy");
    // 10 | click | id=customer_lastname | 
    driver.findElement(By.id("customer_lastname")).click();
    // 11 | type | id=customer_lastname | Abunda
    driver.findElement(By.id("customer_lastname")).sendKeys("Abunda");
    // 12 | click | id=passwd | 
    driver.findElement(By.id("passwd")).click();
    // 13 | type | id=passwd | boyboyabunda
    driver.findElement(By.id("passwd")).sendKeys("boyboyabunda");
    // 14 | click | id=days | 
    driver.findElement(By.id("days")).click();
    // 15 | select | id=days | label=regexp:6\s+
    {
      WebElement dropdown = driver.findElement(By.id("days"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:6\\s+']")).click();
    }
    // 16 | click | id=months | 
    driver.findElement(By.id("months")).click();
    // 17 | select | id=months | label=regexp:February\s
    {
      WebElement dropdown = driver.findElement(By.id("months"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:February\\s']")).click();
    }
    // 18 | click | id=years | 
    driver.findElement(By.id("years")).click();
    // 19 | select | id=years | label=regexp:1988\s+
    {
      WebElement dropdown = driver.findElement(By.id("years"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:1988\\s+']")).click();
    }
    // 20 | click | id=newsletter | 
    driver.findElement(By.id("newsletter")).click();
    // 21 | click | id=optin | 
    driver.findElement(By.id("optin")).click();
    // 22 | click | id=company | 
    driver.findElement(By.id("company")).click();
    // 23 | type | id=company | Testing Co.
    driver.findElement(By.id("company")).sendKeys("Testing Co.");
    // 24 | click | id=address1 | 
    driver.findElement(By.id("address1")).click();
    // 25 | type | id=address1 | Kali Anyar Street. 14054. Testing Co.
    driver.findElement(By.id("address1")).sendKeys("Kali Anyar Street. 14054. Testing Co.");
    // 26 | click | id=address2 | 
    driver.findElement(By.id("address2")).click();
    // 27 | type | id=address2 | Testing Building, 17th Floor
    driver.findElement(By.id("address2")).sendKeys("Testing Building, 17th Floor");
    // 28 | click | id=city | 
    driver.findElement(By.id("city")).click();
    // 29 | type | id=city | Central Jakarta
    driver.findElement(By.id("city")).sendKeys("Central Jakarta");
    // 30 | click | id=id_state | 
    driver.findElement(By.id("id_state")).click();
    // 31 | select | id=id_state | label=Connecticut
    {
      WebElement dropdown = driver.findElement(By.id("id_state"));
      dropdown.findElement(By.xpath("//option[. = 'Connecticut']")).click();
    }
    // 32 | click | id=postcode | 
    driver.findElement(By.id("postcode")).click();
    // 33 | type | id=postcode | 14054
    driver.findElement(By.id("postcode")).sendKeys("14054");
    // 34 | click | id=id_country | 
    driver.findElement(By.id("id_country")).click();
    // 35 | click | id=other | 
    driver.findElement(By.id("other")).click();
    // 36 | type | id=other | No Information
    driver.findElement(By.id("other")).sendKeys("No Information");
    // 37 | click | id=phone | 
    driver.findElement(By.id("phone")).click();
    // 38 | type | id=phone | +114555656
    driver.findElement(By.id("phone")).sendKeys("+114555656");
    // 39 | click | id=phone_mobile | 
    driver.findElement(By.id("phone_mobile")).click();
    // 40 | type | id=phone_mobile | +154574557
    driver.findElement(By.id("phone_mobile")).sendKeys("+154574557");
    // 41 | click | id=alias | 
    driver.findElement(By.id("alias")).click();
    // 42 | click | id=account-creation_form | 
    driver.findElement(By.id("account-creation_form")).click();
    // 43 | type | id=alias | Kali Anyar Street
    driver.findElement(By.id("alias")).sendKeys("Kali Anyar Street");
    // 44 | click | css=#submitAccount > span | 
    driver.findElement(By.cssSelector("#submitAccount > span")).click();
    // 45 | click | linkText=Sign out | 
    driver.findElement(By.linkText("Sign out")).click();
    // 46 | close |  | 
    driver.close();
  }
}
